import { describe, it, expect } from "vitest";
import {
  buildClosuresCsv,
  type FinalFields,
  type RowGeo,
} from "../csv/buildClosuresCsv";
import type { CsvRow, ClosureRange } from "../state/SessionStore";

// ---------------------------------------------------------------------------
// Shared test helpers
// ---------------------------------------------------------------------------

const HEADER =
  "header,reason,start date (yyyy-mm-dd hh:mm),end date (yyyy-mm-dd hh:mm),direction (A to B|B to A|TWO WAY),ignore trafic (Yes|No),segment IDs (id1;id2;...),lon/lat (like in a permalink: lon=xxx&lat=yyy),zoom (2 to 10),MTE ID,comment (optional)";

const DEFAULT_FIELDS: FinalFields = {
  reason: "Tour de Romandie 2026",
  ignoreTraffic: true,
  mteId: "",
  comment: "Autogenerated",
};

function makeRow(
  date: string,
  startTime: string,
  endTime: string,
  segments: number[] | null,
  distance = 0,
): CsvRow {
  return { distance, startTime, endTime, date, segments };
}

function makeGeo(lon: number, lat: number, zoom = 14): RowGeo {
  return { lon, lat, zoom };
}

function makeRange(
  startISO: string,
  endISO: string,
  rowIndex: number,
): ClosureRange {
  return { startISO, endISO, rowIndex };
}

// Parse the output CSV into an array of data rows (skipping the header).
function parseLines(csv: string): string[] {
  return csv.split("\n").filter((l) => l.length > 0 && !l.startsWith("header"));
}

// ---------------------------------------------------------------------------
// 1. Trivial case: 2 rows with entirely disjoint segment sets → 2 output rows
// ---------------------------------------------------------------------------

describe("buildClosuresCsv — trivial disjoint segments", () => {
  it("emits two rows with no merging when segments are completely disjoint", () => {
    const rows: CsvRow[] = [
      makeRow("2026-04-29", "13:00", "13:50", [101, 102]),
      makeRow("2026-04-29", "13:10", "14:00", [201, 202]),
    ];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0), makeGeo(7.1, 46.1)];
    const closuresBySegment: Record<number, ClosureRange[]> = {
      101: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
      102: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
      201: [makeRange("2026-04-29T13:10", "2026-04-29T14:00", 1)],
      202: [makeRange("2026-04-29T13:10", "2026-04-29T14:00", 1)],
    };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);

    expect(lines).toHaveLength(2);
    // First row contains both segment IDs from row 0.
    expect(lines[0]).toContain("101;102");
    expect(lines[0]).toContain("2026-04-29 13:00");
    expect(lines[0]).toContain("2026-04-29 13:50");
    // Second row contains both segment IDs from row 1.
    expect(lines[1]).toContain("201;202");
    expect(lines[1]).toContain("2026-04-29 13:10");
    expect(lines[1]).toContain("2026-04-29 14:00");
  });

  it("starts with the exact required header", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", [101])];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0)];
    const closuresBySegment = {
      101: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
    };
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    expect(csv.split("\n")[0]).toBe(HEADER);
  });
});

// ---------------------------------------------------------------------------
// 2. Same segment in 2 rows but time ranges are disjoint → no merge
// ---------------------------------------------------------------------------

describe("buildClosuresCsv — same segment, disjoint time ranges", () => {
  it("leaves the segment in both original rows when ranges do not overlap", () => {
    // Row 0: 13:00–13:50  |  Row 1: 14:00–14:50  — a 10-minute gap between them.
    const rows: CsvRow[] = [
      makeRow("2026-04-29", "13:00", "13:50", [999, 1]),
      makeRow("2026-04-29", "14:00", "14:50", [999, 2]),
    ];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0), makeGeo(7.1, 46.1)];
    const closuresBySegment: Record<number, ClosureRange[]> = {
      999: [
        makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0),
        makeRange("2026-04-29T14:00", "2026-04-29T14:50", 1),
      ],
      1: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
      2: [makeRange("2026-04-29T14:00", "2026-04-29T14:50", 1)],
    };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);

    // Two original rows, no merged rows.
    expect(lines).toHaveLength(2);
    // Segment 999 appears in both original rows.
    expect(lines[0]).toContain("999");
    expect(lines[1]).toContain("999");
    // No extra row for segment 999.
    const rowsWith999 = lines.filter((l) => l.includes("999"));
    expect(rowsWith999).toHaveLength(2);
  });

  it("treats touching boundaries (end A === start B) as non-overlapping", () => {
    // 13:00–14:00 and 14:00–15:00 touch at 14:00 but must NOT merge.
    const rows: CsvRow[] = [
      makeRow("2026-04-29", "13:00", "14:00", [777]),
      makeRow("2026-04-29", "14:00", "15:00", [777]),
    ];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0), makeGeo(7.0, 46.0)];
    const closuresBySegment: Record<number, ClosureRange[]> = {
      777: [
        makeRange("2026-04-29T13:00", "2026-04-29T14:00", 0),
        makeRange("2026-04-29T14:00", "2026-04-29T15:00", 1),
      ],
    };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);

    // Two original rows kept, no merging.
    expect(lines).toHaveLength(2);
  });
});

// ---------------------------------------------------------------------------
// 3. User's example: segment 298469941 overlaps across two rows
// ---------------------------------------------------------------------------

describe("buildClosuresCsv — user example with overlapping segment", () => {
  // Input:
  //   Row 0 (13:32–14:24): 298469941;298469940;318772212;318772213;318772210;212078376
  //   Row 1 (13:59–14:51): 298469941;335004462;335004461
  //
  // Expected output (3 rows):
  //   Row A: 298469940;318772212;318772213;318772210;212078376  13:32–14:24  (row 0 minus 298469941)
  //   Row B: 335004462;335004461                                13:59–14:51  (row 1 minus 298469941)
  //   Row C: 298469941                                          13:32–14:51  (merged)

  const DATE = "2026-04-29";
  const rows: CsvRow[] = [
    makeRow(DATE, "13:32", "14:24", [
      298469941, 298469940, 318772212, 318772213, 318772210, 212078376,
    ]),
    makeRow(DATE, "13:59", "14:51", [298469941, 335004462, 335004461]),
  ];
  const geos: RowGeo[] = [
    makeGeo(7.05464, 46.17835, 14),
    makeGeo(7.06000, 46.18000, 14),
  ];
  const closuresBySegment: Record<number, ClosureRange[]> = {
    298469941: [
      makeRange(`${DATE}T13:32`, `${DATE}T14:24`, 0),
      makeRange(`${DATE}T13:59`, `${DATE}T14:51`, 1),
    ],
    298469940: [makeRange(`${DATE}T13:32`, `${DATE}T14:24`, 0)],
    318772212: [makeRange(`${DATE}T13:32`, `${DATE}T14:24`, 0)],
    318772213: [makeRange(`${DATE}T13:32`, `${DATE}T14:24`, 0)],
    318772210: [makeRange(`${DATE}T13:32`, `${DATE}T14:24`, 0)],
    212078376: [makeRange(`${DATE}T13:32`, `${DATE}T14:24`, 0)],
    335004462: [makeRange(`${DATE}T13:59`, `${DATE}T14:51`, 1)],
    335004461: [makeRange(`${DATE}T13:59`, `${DATE}T14:51`, 1)],
  };

  it("produces exactly 3 output rows", () => {
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    expect(lines).toHaveLength(3);
  });

  it("row A: row 0 without segment 298469941, time 13:32–14:24", () => {
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    const rowA = lines[0];

    expect(rowA).toContain("2026-04-29 13:32");
    expect(rowA).toContain("2026-04-29 14:24");
    // The 5 remaining segments must all be present.
    expect(rowA).toContain("298469940");
    expect(rowA).toContain("318772212");
    expect(rowA).toContain("318772213");
    expect(rowA).toContain("318772210");
    expect(rowA).toContain("212078376");
    // The merged segment must NOT appear in this row.
    expect(rowA).not.toContain("298469941");
  });

  it("row B: row 1 without segment 298469941, time 13:59–14:51", () => {
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    const rowB = lines[1];

    expect(rowB).toContain("2026-04-29 13:59");
    expect(rowB).toContain("2026-04-29 14:51");
    expect(rowB).toContain("335004462");
    expect(rowB).toContain("335004461");
    expect(rowB).not.toContain("298469941");
  });

  it("row C: dedicated merged row for 298469941, time 13:32–14:51", () => {
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    const rowC = lines[2];

    expect(rowC).toContain("2026-04-29 13:32");
    expect(rowC).toContain("2026-04-29 14:51");
    // Only the merged segment in this row.
    expect(rowC).toContain("298469941");
    expect(rowC).not.toContain("298469940");
    expect(rowC).not.toContain("335004462");
  });

  it("row A uses the lon/lat from row 0 geo", () => {
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    expect(lines[0]).toContain("lon=7.05464&lat=46.17835");
  });

  it("uses finalFields.reason and ignoreTraffic=Yes in output", () => {
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    for (const line of lines) {
      expect(line).toContain("Tour de Romandie 2026");
      expect(line).toContain("Yes");
      expect(line).toContain("TWO WAY");
    }
  });

  it("row C (merged) uses lon/lat from the first contributing row (row 0)", () => {
    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    // Row C uses rowGeo[0] because the earliest ClosureRange for 298469941 has rowIndex=0.
    expect(lines[2]).toContain("lon=7.05464&lat=46.17835");
  });
});

// ---------------------------------------------------------------------------
// 4. Three overlapping ranges of the same segment → one merged range
// ---------------------------------------------------------------------------

describe("buildClosuresCsv — three overlapping ranges collapse to one", () => {
  it("merges three ranges sharing the same segment into a single range", () => {
    const rows: CsvRow[] = [
      makeRow("2026-04-29", "10:00", "11:00", [500]),
      makeRow("2026-04-29", "10:30", "11:30", [500]),
      makeRow("2026-04-29", "11:00", "12:00", [500]),
    ];
    const geos: RowGeo[] = [
      makeGeo(7.0, 46.0),
      makeGeo(7.1, 46.1),
      makeGeo(7.2, 46.2),
    ];
    const closuresBySegment: Record<number, ClosureRange[]> = {
      500: [
        makeRange("2026-04-29T10:00", "2026-04-29T11:00", 0),
        makeRange("2026-04-29T10:30", "2026-04-29T11:30", 1),
        // 11:00–12:00 starts exactly at the end of 10:00–11:00, but
        // 10:30–11:30 overlaps with it, so all three form one group.
        makeRange("2026-04-29T11:00", "2026-04-29T12:00", 2),
      ],
    };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);

    // All three original rows are emptied (only segment 500, which is stripped).
    // One merged row with start=10:00, end=12:00.
    expect(lines).toHaveLength(1);
    expect(lines[0]).toContain("2026-04-29 10:00");
    expect(lines[0]).toContain("2026-04-29 12:00");
    expect(lines[0]).toContain("500");
  });
});

// ---------------------------------------------------------------------------
// 5. Comma in reason → throws Error
// ---------------------------------------------------------------------------

describe("buildClosuresCsv — comma validation", () => {
  it("throws a descriptive Error when reason contains a comma", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", [101])];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0)];
    const closuresBySegment = {
      101: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
    };
    const badFields: FinalFields = {
      reason: "Tour de Romandie, 2026",
      ignoreTraffic: true,
      mteId: "",
      comment: "",
    };

    expect(() =>
      buildClosuresCsv(rows, geos, closuresBySegment, badFields),
    ).toThrow(/comma/i);
  });

  it("throws a descriptive Error when comment contains a comma", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", [101])];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0)];
    const closuresBySegment = {
      101: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
    };
    const badFields: FinalFields = {
      reason: "Tour de Romandie 2026",
      ignoreTraffic: false,
      mteId: "",
      comment: "Auto, generated",
    };

    expect(() =>
      buildClosuresCsv(rows, geos, closuresBySegment, badFields),
    ).toThrow(/comma/i);
  });
});

// ---------------------------------------------------------------------------
// 6. Empty closuresBySegment → only header line
// ---------------------------------------------------------------------------

describe("buildClosuresCsv — empty closuresBySegment", () => {
  it("returns only the header when there are no closures", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", null)];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0)];
    const closuresBySegment: Record<number, ClosureRange[]> = {};

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = csv.split("\n").filter((l) => l.length > 0);

    expect(lines).toHaveLength(1);
    expect(lines[0]).toBe(HEADER);
  });

  it("skips rows with null segments even if closuresBySegment is non-empty", () => {
    const rows: CsvRow[] = [
      makeRow("2026-04-29", "13:00", "13:50", null), // not validated
      makeRow("2026-04-29", "13:10", "14:00", [101]),
    ];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0), makeGeo(7.1, 46.1)];
    const closuresBySegment = {
      101: [makeRange("2026-04-29T13:10", "2026-04-29T14:00", 1)],
    };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const lines = parseLines(csv);
    expect(lines).toHaveLength(1);
    expect(lines[0]).toContain("101");
  });
});

// ---------------------------------------------------------------------------
// 7. Output format spot-checks
// ---------------------------------------------------------------------------

describe("buildClosuresCsv — output format details", () => {
  it("serializes ignoreTraffic=false as 'No'", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", [1])];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0)];
    const closuresBySegment = {
      1: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
    };
    const fields: FinalFields = { ...DEFAULT_FIELDS, ignoreTraffic: false };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, fields);
    expect(csv).toContain(",No,");
  });

  it("formats lon/lat with 5 decimal places", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", [1])];
    const geos: RowGeo[] = [makeGeo(7.1, 46.2, 14)];
    const closuresBySegment = {
      1: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
    };

    const csv = buildClosuresCsv(
      rows,
      geos,
      closuresBySegment,
      DEFAULT_FIELDS,
    );
    expect(csv).toContain("lon=7.10000&lat=46.20000");
  });

  it("emits 'add' as the first column of every data row", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", [1])];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0)];
    const closuresBySegment = {
      1: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
    };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    const dataLine = parseLines(csv)[0];
    expect(dataLine.startsWith("add,")).toBe(true);
  });

  it("ends with a trailing newline", () => {
    const rows: CsvRow[] = [makeRow("2026-04-29", "13:00", "13:50", [1])];
    const geos: RowGeo[] = [makeGeo(7.0, 46.0)];
    const closuresBySegment = {
      1: [makeRange("2026-04-29T13:00", "2026-04-29T13:50", 0)],
    };

    const csv = buildClosuresCsv(rows, geos, closuresBySegment, DEFAULT_FIELDS);
    expect(csv.endsWith("\n")).toBe(true);
  });
});
